var DISQUS=function(h){var e=h.DISQUS||{};e.AssertionError=function(c){this.message=c};e.AssertionError.prototype.toString=function(){return"Assertion Error: "+(this.message||"[no message]")};e.assert=function(c,b,f){if(!c)if(f)h.console&&h.console.log("DISQUS assertion failed: "+b);else throw new e.AssertionError(b);};var b=[];e.define=function(c,g){typeof c==="function"&&(g=c,c="");for(var f=c.split("."),a=f.shift(),d=e,o=(g||function(){return{}}).call({overwrites:function(a){a.__overwrites__=!0;
return a}},h);a;)d=d[a]?d[a]:d[a]={},a=f.shift();for(var j in o)o.hasOwnProperty(j)&&(!o.__overwrites__&&d[j]!==null&&e.assert(!d.hasOwnProperty(j),"Unsafe attempt to redefine existing module: "+j,!0),d[j]=o[j],b.push(function(a,d){return function(){delete a[d]}}(d,j)));return d};e.use=function(c){return e.define(c)};e.cleanup=function(){for(var c=0;c<b.length;c++)b[c]()};return e}(window);
DISQUS.define(function(h,e){var b=h.DISQUS,c=h.document,g=c.getElementsByTagName("head")[0]||c.body,f={running:!1,timer:null,queue:[]};b.defer=function(a,d){function c(){var a=f.queue;if(a.length===0)f.running=!1,clearInterval(f.timer);for(var d=0,b;b=a[d];d++)b[0]()&&(a.splice(d--,1),b[1]())}f.queue.push([a,d]);c();if(!f.running)f.running=!0,f.timer=setInterval(c,100)};b.each=function(a,d){var c=a.length,b=Array.prototype.forEach;if(isNaN(c))for(var g in a)a.hasOwnProperty(g)&&d(a[g],g,a);else if(b)b.call(a,
d);else for(b=0;b<c;b++)d(a[b],b,a)};b.extend=function(a){b.each(Array.prototype.slice.call(arguments,1),function(d){for(var b in d)a[b]=d[b]});return a};b.serializeArgs=function(a){var d=[];b.each(a,function(a,b){a!==e&&d.push(b+(a!==null?"="+encodeURIComponent(a):""))});return d.join("&")};b.isString=function(a){return Object.prototype.toString.call(a)==="[object String]"};b.serialize=function(a,d,c){d&&(a+=~a.indexOf("?")?a.charAt(a.length-1)=="&"?"":"&":"?",a+=b.serializeArgs(d));if(c)return d=
{},d[(new Date).getTime()]=null,b.serialize(a,d);d=a.length;return a.charAt(d-1)=="&"?a.slice(0,d-1):a};b.require=function(a,d,f,e,l){function h(a){if(a.type=="load"||/^(complete|loaded)$/.test(a.target.readyState))e&&e(),q&&clearTimeout(q),b.bean.remove(a.target,p,h)}var k=c.createElement("script"),p=k.addEventListener?"load":"readystatechange",q=null;k.src=b.serialize(a,d,f);k.async=!0;k.charset="UTF-8";(e||l)&&b.bean.add(k,p,h);l&&(q=setTimeout(function(){l()},2E4));g.appendChild(k);return b};
b.requireStylesheet=function(a,d,f){var e=c.createElement("link");e.rel="stylesheet";e.type="text/css";e.href=b.serialize(a,d,f);g.appendChild(e);return b};b.requireSet=function(a,d,c){var g=a.length;b.each(a,function(a){b.require(a,{},d,function(){--g===0&&c()})})};b.injectCss=function(a){var b=c.createElement("style");b.setAttribute("type","text/css");a=a.replace(/\}/g,"}\n");h.location.href.match(/^https/)&&(a=a.replace(/http:\/\//g,"https://"));b.styleSheet?b.styleSheet.cssText=a:b.appendChild(c.createTextNode(a));
g.appendChild(b)}});
DISQUS.define("JSON",function(){function h(a){return a<10?"0"+a:a}function e(b){a.lastIndex=0;return a.test(b)?'"'+b.replace(a,function(a){var b=j[a];return typeof b==="string"?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+b+'"'}function b(a,c){var f,h,j,m,k=d,n,i=c[a];i&&typeof i==="object"&&typeof i.toJSON==="function"&&!g&&(i=i.toJSON(a));typeof l==="function"&&(i=l.call(c,a,i));switch(typeof i){case "string":return e(i);case "number":return isFinite(i)?String(i):"null";case "boolean":case "null":return String(i);
case "object":if(!i)return"null";d+=o;n=[];if(Object.prototype.toString.apply(i)==="[object Array]"){m=i.length;for(f=0;f<m;f+=1)n[f]=b(f,i)||"null";j=n.length===0?"[]":d?"[\n"+d+n.join(",\n"+d)+"\n"+k+"]":"["+n.join(",")+"]";d=k;return j}if(l&&typeof l==="object"){m=l.length;for(f=0;f<m;f+=1)h=l[f],typeof h==="string"&&(j=b(h,i))&&n.push(e(h)+(d?": ":":")+j)}else for(h in i)Object.hasOwnProperty.call(i,h)&&(j=b(h,i))&&n.push(e(h)+(d?": ":":")+j);j=n.length===0?"{}":d?"{\n"+d+n.join(",\n"+d)+"\n"+
k+"}":"{"+n.join(",")+"}";d=k;return j}}var c={},g=!1;if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+h(this.getUTCMonth()+1)+"-"+h(this.getUTCDate())+"T"+h(this.getUTCHours())+":"+h(this.getUTCMinutes())+":"+h(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var f=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
a=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,d,o,j={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},l;c.stringify=function(a,c,g){var f;o=d="";if(typeof g==="number")for(f=0;f<g;f+=1)o+=" ";else typeof g==="string"&&(o=g);if((l=c)&&typeof c!=="function"&&(typeof c!=="object"||typeof c.length!=="number"))throw Error("JSON.stringify");return b("",{"":a})};c.parse=function(a,b){function c(a,
d){var g,f,e=a[d];if(e&&typeof e==="object")for(g in e)Object.hasOwnProperty.call(e,g)&&(f=c(e,g),f!==void 0?e[g]=f:delete e[g]);return b.call(a,d,e)}var d,a=String(a);f.lastIndex=0;f.test(a)&&(a=a.replace(f,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return d=eval("("+a+")"),
typeof b==="function"?c({"":d},""):d;throw new SyntaxError("JSON.parse");};var m={a:[1,2,3]},k,p;if(Object.toJSON&&Object.toJSON(m).replace(/\s/g,"")==='{"a":[1,2,3]}')k=Object.toJSON;typeof String.prototype.evalJSON==="function"&&(m='{"a":[1,2,3]}'.evalJSON(),m.a&&m.a.length===3&&m.a[2]===3&&(p=function(a){return a.evalJSON()}));(function(){var a=[1,2,3];typeof a.toJSON==="function"&&(a=a.toJSON(),g=!(a&&a.length===3&&a[2]===3))})();if(g||!k||!p)return{stringify:c.stringify,parse:c.parse};return{stringify:k,
parse:p}});
DISQUS.define("Bus",function(){function h(a){a=a.split("/");return a[0]+"//"+a[2]}var e=DISQUS.use("JSON"),b=window.location.hash.slice(1),c=window.parent,g=document.referrer,f={};f.client=h(document.location.href);f.host=g?h(g):f.client;return{origins:f,postMessage:function(a){a.sender=b;a=e.stringify(a);c.postMessage(a,f.host)},sendHostMessage:function(a,b){b=b||[];DISQUS.Bus.postMessage({scope:"host",name:a,data:b})},sendGlobalMessage:function(a,b){b=b||[];DISQUS.Bus.postMessage({scope:"global",name:a,
data:b})}}});_.extend(DISQUS.Bus,Backbone.Events);$(document).ready(function(){var h=window.addEventListener?window.addEventListener:window.attachEvent,e=window.addEventListener?"message":"onmessage";if(!h)throw Error("No event support.");h(e,function(b){var c=DISQUS.Bus,g=b.origin;if(!(g!=c.origins.client&&g!=c.origins.host)){var f;try{f=DISQUS.JSON.parse(b.data)}catch(a){return}b=f.data;switch(f.scope){case "client":c.trigger(b.eventName,b.data)}}},!1)});
DISQUS.define(function(h,e){var b={blocks:{},ISO_8601:"YYYY-MM-DDTHH:mm:ssZ",apiKey:"E8Uh5l5fHZ6gD8U3KycjAIAk46f68Zw7C6eW8WSjZvCLXebZ7p0r1yrYDrLilk2F",bean:require("bean"),debug:!1,browser:{mobile:navigator.userAgent.match(/Android|webOS|iPhone|iPad|iPod|BlackBerry/i)},modules:{},strings:{translations:{}}};b.strings.get=_.bind(function(b){var c=this.translations[b];return c!==e?c:b},b.strings);b.interpolate=function(b,c){return b.replace(/%\(\w+\)s/g,function(a){var a=a.slice(2,-2),d="";a in c?d=
c[a]!==e&&c[a]!==null?c[a].toString():"":DISQUS.logError&&DISQUS.logError("Key `"+a+"` not found in context for: ",b);return d})};b.addBlocks=function(){return function(b){b(DISQUS)}};b.templateGlobals={urls:DISQUS.use("urls"),sso:null,trans:b.strings.get};b.renderBlock=function(c,f){return DISQUS.blocks[c](b.templateGlobals,f)};b.assureOffset=function(b){return b.indexOf("+")>=0?b:b+"+00:00"};var c=b.Builder=function(){this.accum=[]};_.extend(c.prototype,{put:function(b){this.accum.push(b)},esc:function(b){return String(b).replace(/&/g,
"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")},compile:function(){return this.accum.join("")}});return b});
DISQUS.define("urls",function(){var h=DISQUS.debug?"/js/src/embed/next/vglnk.js":"/build/next/alfie.js",e=encodeURIComponent(document.referrer),b={root:"http://disqus.com",media:"http://mediacdn.disqus.com/1352251429",loading:"http://mediacdn.disqus.com/1352251429/html/simple-loading.html",realertime:"",login:"https://disqus.com/next/login/",api:"http://disqus.com/api/3.0/",apiSecure:"https://disqus.com/api/3.0/",logout:"http://disqus.com/logout/?redirect="+e,editProfile:"http://disqus.com/account/",
verifyEmail:"https://disqus.com/next/verify/",authorize:"https://disqus.com/api/oauth/2.0/authorize/",moderate:"http://disqus.com/admin/moderate/",oauth:{twitter:"http://disqus.com/_ax/twitter/begin/",google:"http://disqus.com/_ax/google/begin/",facebook:"http://disqus.com/_ax/facebook/begin/"},avatar:{generic:"http://mediacdn.disqus.com/1352251429/images/noavatar92.png"},linkAffiliatorClient:"http://mediacdn.disqus.com/1352251429"+h};window.location.protocol==="https:"&&(b=_.extend(b,{root:"",media:"",
loading:"/html/simple-loading.html",realertime:b.realertime.replace("http://","https://"),api:b.apiSecure,logout:"https://disqus.com/logout/?redirect="+e,editProfile:"https://disqus.com/account/",moderate:"https://disqus.com/admin/moderate/",oauth:{twitter:"https://disqus.com/_ax/twitter/begin/",google:"https://disqus.com/_ax/google/begin/",facebook:"http://disqus.com/_ax/facebook/begin/"},avatar:{generic:"/images/noavatar92.png"},linkAffiliatorClient:""+h}));return b});
DISQUS.define("api",function(){function h(b){function g(a){var e=a.originalEvent.origin;DISQUS.urls.apiSecure.slice(0,e.length)===e&&(a=DISQUS.JSON.parse(a.originalEvent.data),a.requestId===f&&(e=a.code===0?b.success:b.error,delete a.requestId,(e||function(){})(a),document.body.removeChild(h),document.body.removeChild(d),$(window).unbind("message",g)))}var f=_.uniqueId(),a=document.createElement("div"),d=document.createElement("form"),e="frame_"+f,h;a.innerHTML='<iframe name="'+e+'"></iframe>';h=
a.childNodes[0];d.target=e;d.action=b.url.replace(".json",".pm");d.method=b.method||"GET";b.data=_.extend(b.data,{callback:f,referrer:document.referrer});_.each(b.data,function(a,b){a===!0?a=[1]:a===!1?a=[0]:a===null?a=[""]:_.isArray(a)||(a=[a]);_.each(a,function(a){var c=document.createElement("input");c.type="hidden";c.name=b;c.value=a;d.appendChild(c)})});$(window).bind("message",g);document.body.appendChild(h);document.body.appendChild(d);d.submit()}function e(c){c=_.defaults(c,b);c.data=c.data||
{};c.data.api_key=DISQUS.apiKey;$.ajax(c)}var b={};return{defaults:function(c){var e,f,a;for(e in c)f=c[e],a=b[e],_.isObject(f)&&_.isObject(a)?_.extend(a,f):b[e]=f},getURL:function(b,e){e=e||{};if(e.secure||window.location.protocol==="https:")return DISQUS.urls.apiSecure+b;return DISQUS.urls.api+b},ajax:e,call:function(b,g){g=g||{};g.url=DISQUS.api.getURL(b,{secure:g.secure});g.data=_.extend(g.data||{},{api_key:DISQUS.apiKey});(g.secure?h:e)(g)}}});
(function(h){var e=DISQUS.Bus,b=DISQUS.api.getURL("internal/switches/list.jsonp");h.switches_jsonp_cb=function(b){e.sendHostMessage("switches.received",b.response)};e.on("fetch",function(c){c=c||{};c.data=c.data||{};c.data.callback="switches_jsonp_cb";c.data.api_key=DISQUS.apiKey;c=DISQUS.serialize(b,c.data,!1);DISQUS.require(c)});e.sendHostMessage("ready")})(this);